### ISSUE TITLE
payol migration issue

### ISSUE THREAD

**Issue by shantilal-narola** [payolapayments/payola#338]
I am trying to implement the payola-payment subscription in the rails project.I have tried to use the gem 'payola-payments' but after installing bundle I have tried to run rake db:migrate command but i am facing error like: NoMethodError: undefined method `event_retriever=' for StripeEvent:Module Did you mean? event_filter=

I have found a solution to use "gem 'payola-payments', :git => 'git@github.com:payolapayments/payola.git'" but after that i am facing error in migration like: Caused by: NoMethodError: undefined method `[]' for # and the table is not getting generated for the payola.

**Comment by Alagaesia93** [comment]
+1

**Comment by malditojavi** [comment]
try https://github.com/payolapayments/payola/issues/335#issuecomment-373308121

**Comment by gerwitz** [comment]
@nerboda fixed this, but there is no corresponding release. Try this in your `Gemfile` to get the fixed version:

````
gem 'payola-payments', git: 'https://github.com/payolapayments/payola.git', ref: '08bd7bc'
````

Note this will fix you to a specific commit state: you'll want to watch this repository closely for security fixes!

**Comment by gerwitz** [comment]
I am also having this problem on Rails 4.2. It appears that af67b1a4601932f23d0533327557280bc5f5c756 made Payola require Rails 5.0, somewhat ironically.

**Comment by Rhoxio** [comment]
For those of you trying to get this to work with Rails 4.2 - I've been running version 1.4.0 on Rails 4.2 and Ruby 2.3.1 for a good while now. The initializers and migrations ran fine at inception and appear to run fine now. [Payola 1.4.0](https://rubygems.org/gems/payola-payments/versions/1.4.0)

A problem with this specific version is that zipcode validations that fail when a transaction is taking place will cause your server to throw a 404 (some nil value) and produce no status messages like the other error responses. This can be circumvented by setting Stripe to not validate the zipcode on the card (leave the cvc alone - it works just fine and is the only other presence validator) if you aren't into monkey patching the lib.
